kubernetesClusterDomain: cluster.local
manager:
  kubeRbacProxy:
    args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.15.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  manager:
    args:
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=127.0.0.1:8080
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: gcr.io/whitestack/whitecruiser/whitesdn-controller
      tag: bahia
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
whitesdnCaCert:
  certPem: ""
whitesdnConfig:
  availabilityZone: WCRUISER_test-zone
  insecureSkipVerify: "false"
  url: http://whitesdn.ocp2.tcloud.whitestack.com/
  user: apiuser
whitesdnSecrets:
  password: ""
whitesdnState:
  whitesdnStateJson: |-
    {
      "nodes": [
        {
          "name": "",
          "ports": [
            {
                "device_id": "",
                "interface_name": ""
            },
            {
                "device_id": "",
                "interface_name": ""
            }
          ]
        }
      ]
    }
