apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-manager
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: whitesdn-controller
    app.kubernetes.io/part-of: whitesdn-controller
    control-plane: manager
  {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      control-plane: manager
    {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: manager
      {{- include "helm.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.manager.kubeRbacProxy.args | nindent 8 }}
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.manager.kubeRbacProxy.image.repository }}:{{ .Values.manager.kubeRbacProxy.image.tag
          | default .Chart.AppVersion }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {{- toYaml .Values.manager.kubeRbacProxy.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.manager.kubeRbacProxy.containerSecurityContext
          | nindent 10 }}
      - args: {{- toYaml .Values.manager.manager.args | nindent 8 }}
        command:
        - /manager
        env:
        - name: WHITESDN_URL
          valueFrom:
            configMapKeyRef:
              key: URL
              name: {{ include "helm.fullname" . }}-whitesdn-config
        - name: WHITESDN_USER
          valueFrom:
            configMapKeyRef:
              key: USER
              name: {{ include "helm.fullname" . }}-whitesdn-config
        - name: WHITESDN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: {{ include "helm.fullname" . }}-whitesdn-secrets
        - name: WHITESDN_AZ
          valueFrom:
            configMapKeyRef:
              key: AVAILABILITY_ZONE
              name: {{ include "helm.fullname" . }}-whitesdn-config
        - name: INSECURE_SKIP_VERIFY
          valueFrom:
            configMapKeyRef:
              key: INSECURE_SKIP_VERIFY
              name: {{ include "helm.fullname" . }}-whitesdn-config
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.manager.manager.image.repository }}:{{ .Values.manager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.manager.manager.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.manager.manager.containerSecurityContext |
          nindent 10 }}
        volumeMounts:
        - mountPath: /data
          name: whitesdn-state
        - mountPath: /certs
          name: whitesdn-ca-cert
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "helm.fullname" . }}-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: {{ include "helm.fullname" . }}-whitesdn-state
        name: whitesdn-state
      - configMap:
          name: {{ include "helm.fullname" . }}-whitesdn-ca-cert
        name: whitesdn-ca-cert