apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: whitesdn-controller
    app.kubernetes.io/part-of: whitesdn-controller
    control-plane: manager
  {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: manager
  {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}