apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.fullname" . }}-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: whitesdn-controller
    app.kubernetes.io/part-of: whitesdn-controller
  {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.manager.serviceAccount.annotations | nindent 4 }}