apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-whitesdn-ca-cert
  labels:
  {{- include "helm.labels" . | nindent 4 }}
data:
  cert.pem: {{ .Values.whitesdnCaCert.certPem | quote }}