apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-whitesdn-state
  labels:
  {{- include "helm.labels" . | nindent 4 }}
data:
  whitesdn_state.json: {{ .Values.whitesdnState.whitesdnStateJson | toYaml | indent
    1 }}