apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-whitesdn-secrets
  labels:
  {{- include "helm.labels" . | nindent 4 }}
stringData:
  PASSWORD: {{ required "whitesdnSecrets.password is required" .Values.whitesdnSecrets.password
    | quote }}
type: Opaque